sudo: false
language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "oGTh2CWeXxdH1EOcrtgBl7xNt1TtYBGEVRObKpffJDpoWMi/70FKFL77KhmccbsQEtIdhR5vkaen40EMULY3pIZNCKUt/4yncnDb6okfJIiQGydq+uQsx0YlVIyDnQlrQ/AxhIm8vrFJINYO0ZosD2dQ1px/hwgmpSpDVEC1AbAFbgGlYL4uDmBoHQExYn/bQILvgv1xnNt6HW1KOQ+vmWBgwrCjqM3nRJ7WEqg8qM0CEWtaUrIxxvvoVN/JcF6eA7LfpDiAOtlyLbl8HD7GuFTNittleMGlpHioRNTWzpVZprIim0G5J4WjNd4amHClG0TUJr6em4OuRy/lMyPsOsonCG8eXc5tEyPOxTvaiVrJldFUliUzCQsPessrAdsCQ+LCHUhgji05ygEBx1ZCUR8sXU3dbFnduyH2+DX1BawOGau1bP1qTu9AwL08Sa0gEZwhjDmDtt9kt92CrgEC8nh+Gd/ER29vbkFkdhAxNYc4Y3vZcUWZrJYZmG3ehVdr+EfWE6h02HDWoVj/mnjXvQhnvRqb2YIYa7qunBQ0SQZ8x6rnF3qLhM+g18L05jx3Py2EZzqeE2red7mq7MxMzzs2CD5gn0bscabQ2QZ3dRzHCFrzRonGwHwRcVA/pqJRPSWMRPRc5Lq5jSI0y6YqvXTmqop1reoNTNEbKZ/STmw="

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        coverity_scan:
          project:
            name: nikkikom/programming-exercise-c-1
            description: Build submitted via Travis CI
            version: 1.0
          notification_email: nikkikom@gmail.com
          build_command_prepend: "cov-configure --template --compiler clang-3.8 --comptype clangcc && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE .."
          build_command: "cmake --build . --config RELEASE"
          branch_pattern: coverity_scan
      compiler: clang
      env: COMPILER_NAME=clang O_CC=clang-3.8 BUILD_TYPE=RELEASE

cache:
  directories:
    - cache

install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      if [ "!" -x cache/cmake/bin/cmake ]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir -p cache/cmake
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cache/cmake
      fi
      export PATH="$TRAVIS_BUILD_DIR/cache/cmake/bin:$PATH"
    elif [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if "!" brew ls --version cmake; then
        brew install cmake
      fi
    fi

before_script:
  - uname -a
  - which cmake
  - cmake --version
  - echo $CC $COMPILER_NAME
  - which $CC
  - $CC --version

before_install:
  - export CC=$O_CC

script:
  - echo "Skipping regular build since Coverity Scan is active"

#after_script:
#  - cat build/cov-int/build-log.txt
